https://pytorch.org/docs/stable/torch.html

In [1]:
!pip3 install torch==0.4.0
!pip3 install torchvision==0.2.1
# !pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl 

    100% |████████████████████████████████| 484.0MB 33kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5c9fc000 @  0x7fcef241b1c4 0x46d6a4 0x5fcbcc 0x4c494d 0x54f3c4 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54e4c8
    100% |████████████████████████████████| 61kB 5.0MB/s 
    100% |████████████████████████████████| 2.0MB 12.6MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


# Tensorsオブジェクト

In [0]:
from __future__ import print_function
import torch
import numpy as np

## テンソル型かを確認する


```
torch.is_tensor(obj)
```

obj：テストするオブジェクト


objがPyTorchテンソルであればTrueを返す

In [3]:
x = torch.Tensor(5, 3)
torch.is_tensor(x)

True

## torch.is_storage（obj ）

objがPyTorchストレージオブジェクトであればTrueを返します。

obj：テストするオブジェクト


In [2]:
x = torch.Storage(5)
torch.is_storage(x)

True

# テンソルの初期の型を設定する


```
torch.set_default_dtype(d)
```

d：浮動小数点dtypeをデフォルトにする




デフォルトの浮動小数点dtypeをdに設定します。この型は、torch.tensor（）の型推論のデフォルトの浮動小数点型として使用されます。

In [4]:
torch.tensor([1.2, 3]).dtype

torch.float32

In [5]:
torch.set_default_dtype(torch.float64)
torch.tensor([1.2, 3]).dtype

torch.float64

# 入力テンソル内の要素の総数を取得する


```
torch.numel(input) → int
```

input：インプットするテンソル



入力テンソル内の要素の総数を返します。

In [8]:
x = torch.randn(1, 2, 3, 1)
torch.numel(x)

6

In [9]:
x = torch.zeros(4,4)
torch.numel(x)

16

# torch.set_flush_denormal(mode) → bool

mode：フラッシュ非正規化モードを有効にするかどうかを制御します。


CPU上の非正規化浮動小数点数を無効にします。 システムが非正規化数のフラッシュをサポートしていて、フラッシュ非正規化モードが正常に設定されている場合はTrueを返します。 set_flush_denormal（）は、SSE3をサポートするx86アーキテクチャでのみサポートされています。

In [10]:
torch.set_flush_denormal(True)

True

In [0]:
torch.tensor([1e-323], dtype=torch.float64)

tensor([ 0.])

In [0]:
torch.set_flush_denormal(False)

True

In [0]:
torch.tensor([1e-323], dtype=torch.float64)

tensor(9.88131e-324 *
       [ 1.0000])

# データでテンソルを構築する

```
torch.tensor(data, dtype=None, device=None, requires_grad=False) → Tensor
```

data：テンソルの初期データ。リスト、タプル、NumPy ndarray、スカラー、その他の型になります    
dtype：返されるテンソルの望ましいデータ型デフォルト：Noneの場合、データからデータ型を推定します。    

device：返されるテンソルの望ましいデバイス。デフォルト：Noneの場合、現在のデバイスをデフォルトのテンソルタイプに使用します。デバイスはCPUテンソルタイプのCPUとなり、現在のCUDAデバイスはCUDAテンソルタイプ用です。    

requires_grad：autogradが返されたテンソルの操作を記録する必要がある場合。デフォルト：False。




In [0]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[ 0.1000,  1.2000],
        [ 2.2000,  3.1000],
        [ 4.9000,  5.2000]])

In [0]:
torch.tensor([0, 1])  # データの型推論

tensor([ 0,  1])

In [0]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                 dtype=torch.float64,
                 device=torch.device('cuda:0'))

tensor([[ 0.1111,  0.2222,  0.3333]], device='cuda:0')

In [0]:
#スカラー
torch.tensor(3.14159)

tensor(3.1416)

In [0]:
#空のテンソルを作成
torch.tensor([])

tensor([])

# numpy.ndarrayからTensorを作成する

numpy.ndarrayからテンソルを作成する。
返されたテンソルとndarrayは同じメモリを共有します。テンソルの変更はndarrayに反映され、その逆も同様です。返されるテンソルはサイズ変更できません。


ndarray：numpy.ndarray


```
torch.from_numpy(ndarray) → Tensor
```


In [19]:
x = np.array([1, 2, 3])
t = torch.from_numpy(x)
t

tensor([ 1,  2,  3])

In [20]:
t[0] = -1
x

array([-1,  2,  3])

# スカラー値0で満たされたテンソルを返す

torch.zeros(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor


シェイプは可変引数サイズで定義されます。


size：出力テンソルの形状を定義する整数のシーケンス。引数の数やリストやタプルのようなコレクションにすることができます。    
out：出力テンソル    
dtype：返されるテンソルの望ましいデータ型デフォルト：Noneの場合、グローバルデフォルトを使用します。    
layout：返されたTensorの望ましいレイアウト。デフォルト：torch.strided。    
device：返されるテンソルの望ましいデバイス。デフォルト：Noneの場合、現在のデバイスをデフォルトのテンソルタイプに使用します。デバイスはCPUのテンソルタイプのCPUとなり、現在のCUDAデバイスはCUDAのテンソルタイプのデバイスになります。    
requires_grad：autogradが返されたテンソルの操作を記録する必要がある場合。デフォルト：False。




In [21]:
torch.zeros(2, 3)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [0]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

# 入力と同じサイズのスカラー値0で満たされたテンソルを返します。

torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor

input：入力のサイズは出力テンソルのサイズを決定する    
dtype：返されるTensorの望ましいデータ型デフォルト：なしの場合、デフォルトは入力のdtypeになります。    
layout：戻りテンソルの望ましいレイアウト。デフォルト：なしの場合、デフォルトは入力のレイアウトになります。    
device：返されるテンソルの望ましいデバイス。デフォルト：Noneの場合、デフォルトで入力デバイスになります。    
requires_grad：autogradが返されたテンソルの操作を記録する必要がある場合。デフォルト：False。



In [14]:
input = torch.empty(2, 3)
input

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [15]:
torch.zeros_like(input)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

# インデックス、スライシング、結合



## 指定された次元の指定されたシーケンステンソル同士を連結


```
torch.cat(seq, dim=0, out=None) → Tensor
```

seq：同じタイプのテンソルの任意のPythonシーケンス。提供される空でないテンソルは、cat次元を除いて同じ形状でなければなりません。    
dim：テンソルが連結されている次元    
out：出力テンソル    


In [16]:
x = torch.randn(2, 3)
x

tensor([[ 0.2126,  0.6063,  0.7730],
        [-1.1140, -0.1688,  0.4510]])

In [17]:
torch.cat((x, x, x), 0)

tensor([[ 0.2126,  0.6063,  0.7730],
        [-1.1140, -0.1688,  0.4510],
        [ 0.2126,  0.6063,  0.7730],
        [-1.1140, -0.1688,  0.4510],
        [ 0.2126,  0.6063,  0.7730],
        [-1.1140, -0.1688,  0.4510]])

In [18]:
torch.cat((x, x, x), 1)

tensor([[ 0.2126,  0.6063,  0.7730,  0.2126,  0.6063,  0.7730,  0.2126,
          0.6063,  0.7730],
        [-1.1140, -0.1688,  0.4510, -1.1140, -0.1688,  0.4510, -1.1140,
         -0.1688,  0.4510]])

## テンソルを特定の数のチャンクに分割する

```
torch.chunk(tensor, chunks, dim=0) → List of Tensors

```

## インデックスを指定して任意のテンソルを返すには


LongTensorであるindexのエントリを使用して、次元dimに沿って入力テンソルをインデックスする新しいテンソルを返す


```
torch.index_select(input, dim, index, out=None) → Tensor

```

input：入力テンソル    
dim：インデックスを作成するディメンション    
index：    



In [15]:
x = torch.randn(3, 4)
x

tensor([[ 1.6076, -1.3436, -1.6549,  0.4366],
        [-1.7768,  1.0721, -1.9480,  2.0861],
        [ 1.4206, -0.9619,  1.3981, -0.6471]])

In [0]:
indices = torch.tensor([1])

In [17]:
torch.index_select(x, 0, indices)

tensor([[-1.7768,  1.0721, -1.9480,  2.0861]])

In [18]:
torch.index_select(x, 1, indices)

tensor([[-1.3436],
        [ 1.0721],
        [-0.9619]])

## サイズ1の入力のすべての次元が削除されたテンソルを返す

```
torch.squeeze(input, dim=None, out=None) → Tensor
```

input：入力テンソル    
dim：指定されている場合、入力はこの次元でのみ絞られます    
out：出力テンソル    


In [3]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [4]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [7]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [11]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [9]:
y = torch.squeeze(x, 3)
y.size()

torch.Size([2, 1, 2, 2])

## 新しい次元に沿ってテンソルのシーケンスを連結

```
torch.stack(seq, dim=0, out=None) → Tensor
```

## テンソルを転置する


```
torch.t(input, out=None) → Tensor
```

input：入力テンソル    


In [0]:
x = torch.randn(2, 3)
x

tensor([[ 0.8700,  1.5896, -0.5968],
        [-1.4658,  0.2223,  0.4184]])

In [0]:
torch.t(x)

tensor([[ 0.8700, -1.4658],
        [ 1.5896,  0.2223],
        [-0.5968,  0.4184]])

## テンソルの次元を入れ替える


```
torch.transpose(input, dim0, dim1, out=None) → Tensor

```

input：入力テンソル    
dim0：転置される第1の次元    
dim1：転置される第2の次元    


In [0]:
x = torch.randn(2, 3)
x

tensor([[-0.3526, -1.8649, -0.0978],
        [-1.3703,  0.2345,  1.2297]])

In [0]:
torch.transpose(x, 0, 1)

tensor([[-0.3526, -1.3703],
        [-1.8649,  0.2345],
        [-0.0978,  1.2297]])

## 指定された位置にサイズ1の次元を挿入するには

```
torch.unsqueeze(input, dim, out=None) → Tensor
```

input：入力テンソル    
dim：シングルトン次元を挿入するインデックス    
out：出力テンソル    


In [12]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[ 1,  2,  3,  4]])

In [13]:
torch.unsqueeze(x, 1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4]])

# ランダムサンプリング

## 乱数を生成するためのシードを設定

```
torch.manual_seed(seed)
```

## Bernoulli分布からのバイナリ乱数（0または1）を生成するには

```
torch.bernoulli(input, out=None) → Tensor
```

input：ベルヌーイ分布の確率値の入力テンソル    
out：出力テンソル    

In [14]:
x = torch.empty(3, 3).uniform_(0, 1) # generate a uniform random matrix with range [0, 1]
x

tensor([[ 0.3117,  0.1804,  0.0734],
        [ 0.8726,  0.0789,  0.7505],
        [ 0.7156,  0.5328,  0.0979]])

In [15]:
torch.bernoulli(x)

tensor([[ 0.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  1.,  0.]])

In [16]:
x = torch.ones(3, 3) # probability of drawing "1" is 1
torch.bernoulli(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [17]:
x = torch.zeros(3, 3) # probability of drawing "1" is 0
torch.bernoulli(x)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

## 多項式確率分布からサンプリングされたテンソルを生成するには


```
torch.multinomial(input, num_samples, replacement=False, out=None) → LongTensor

```

input：確率を含む入力テンソル    
num_samples：描画するサンプル数    
replacement：置換するかどうかで描画するかどうか    
out：出力テンソル    


In [0]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float) # create a tensor of weights
torch.multinomial(weights, 4)

tensor([ 1,  2,  0,  0])

In [0]:
torch.multinomial(weights, 4, replacement=True)

tensor([ 1,  1,  2,  1])

## 正規分布からサンプリングされたテンソルを生成するには

書式１

```
torch.normal(mean, std, out=None) → Tensor
```

mean：要素ごと平均のテンソル    
std：要素ごと標準偏差のテンソル    
out：出力テンソル    


In [0]:
torch.normal(mean=torch.arange(1, 11), std=torch.arange(1, 0, -0.1))

tensor([  0.4397,   0.9406,   3.3330,   4.2483,   5.5898,   5.6349,
          6.6218,   8.1603,   8.9097,  10.0206])

書式２    

```
torch.normal(mean=0.0, std, out=None) → Tensor
```

mean：全ての分布の平均    
std：要素ごとの標準偏差のテンソル    
out：出力テンソル    


In [18]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([-1.0148,  0.0795,  7.9227,  9.5850,  7.2037])


書式３

```
torch.normal(mean, std=1.0, out=None) → Tensor
```

mean：要素ごと平均のテンソル    
std：全ての分布の標準偏差    
out：出力テンソル    


In [19]:
torch.normal(mean=torch.arange(1., 6.))

tensor([ 2.7136,  0.1551,  3.4284,  5.2034,  4.6626])

## 区間[0,1]上の一様分布から乱数で満たされたテンソルを返します。

```
torch.rand(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
```


sizes：出力テンソルの形状を定義する整数のシーケンス。引数の数やリストやタプルのようなコレクションにすることができます。    




In [0]:
torch.rand(4)

tensor([ 0.6492,  0.2481,  0.9398,  0.0428])

In [0]:
torch.rand(2, 3)

tensor([[ 0.6558,  0.1538,  0.0610],
        [ 0.1156,  0.7963,  0.1621]])

## 平均0と分散1の正規分布からの乱数で満たされたテンソルを返します

```
torch.randn(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
```

sizes：出力テンソルの形状を定義する整数のシーケンス。引数の数やリストやタプルのようなコレクションにすることができます。    
out：出力テンソル    
dtype：返されるテンソルのデータ型。デフォルト：Noneの場合グローバルデフォルトを使用します。    
layout：返されるTensorのレイアウト。デフォルト：torch.strided。    
device：返されるテンソルの望ましいデバイス。デフォルト：Noneの場合、現在のデバイスをデフォルトのテンソルタイプに使用します。デバイスはCPUテンソルタイプのCPUとなり、現在のCUDAデバイスはCUDAテンソルタイプ用です。    

requires_grad：autogradが返されたテンソルの操作を記録する必要がある場合。デフォルト：False。


In [0]:
torch.randn(4)

tensor([ 0.8521, -1.5651,  0.5913, -0.9930])

In [0]:
torch.randn(2, 3)

tensor([[-1.4987,  1.1867, -1.1795],
        [ 0.4344,  1.5043,  0.3580]])

## 0からn-1までの整数のランダム置換を返します。

```
torch.randperm(n, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False) → LongTensor
```

n：上限（排他的・・？）    
out：出力テンソル    
dtype：返されるテンソルのデータ型。デフォルト：Noneの場合グローバルデフォルトを使用します。    
layout：返されるTensorのレイアウト。デフォルト：torch.strided。    
device：返されるテンソルの望ましいデバイス。デフォルト：Noneの場合、現在のデバイスをデフォルトのテンソルタイプに使用します。デバイスはCPUテンソルタイプのCPUとなり、現在のCUDAデバイスはCUDAテンソルタイプ用です。    

requires_grad：autogradが返されたテンソルの操作を記録する必要がある場合。デフォルト：False。


In [0]:
torch.randperm(4)

tensor([ 1,  3,  0,  2])

# オブジェクトの保存と読み込み

## オブジェクトをディスクファイルに保存

```
torch.save(obj, f, pickle_module=<module 'pickle' from '/private/home/soumith/anaconda3/lib/python3.6/pickle.py'>, pickle_protocol=2)
```

obj：オブジェクトを保存する    
f：ファイルのようなオブジェクト、またはファイル名を含む文字列
pickle_module：メタデータとオブジェクトをpickle化するためのモジュール    

pickle_protocol：デフォルトのプロトコルを上書きするように指定することができます

In [0]:
import io
# Save to file
x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, 'tensor.pt')

In [0]:
!ls

datalab  tensor.pt


In [0]:
# Save to io.BytesIO buffer
buffer = io.BytesIO()
torch.save(x, buffer)

## torch.save()で保存されたオブジェクトを読み込む


```
torch.load(f, map_location=None, pickle_module=<module 'pickle' from '/private/home/soumith/anaconda3/lib/python3.6/pickle.py'>)
```

f：ファイルライクなオブジェクト、またはファイル名を含む文字列    
map_location：関数、torch.device、文字列、または格納場所を再マップする方法を指定するdict    
pickle_module：メタデータとオブジェクトのunpickleに使用されるモジュール    

In [0]:
torch.load('tensors.pt')
# Load all tensors onto the CPU
torch.load('tensors.pt', map_location='cpu')
# Load all tensors onto the CPU, using a function
torch.load('tensors.pt', map_location=lambda storage, loc: storage)
# Load all tensors onto GPU 1
torch.load('tensors.pt', map_location=lambda storage, loc: storage.cuda(1))
# Map tensors from GPU 1 to GPU 0
torch.load('tensors.pt', map_location={'cuda:1':'cuda:0'})
# Load tensor from io.BytesIO object
with open('tensor.pt') as f:
        buffer = io.BytesIO(f.read())
torch.load(buffer)

FileNotFoundError: ignored

# 並列処理


## CPU操作の並列化に使用されるOpenMPスレッドの数を取得します。

# 勾配計算を局所的に無効にする

Locally disabling gradient computation

# 数学演算

## 入力テンソルの要素的な絶対値を計算

```
torch.abs(input, out=None) → Tensor
```


In [0]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([ 1,  2,  3])

## 入力の各要素にスカラー値を加算し、新しい結果テンソルを返します

```
torch.add()
```

In [0]:
a = torch.randn(4)
a

tensor([ 0.6820,  1.0504,  1.7212, -0.0159])

In [0]:
torch.add(a, 20)

tensor([ 20.6820,  21.0504,  21.7212,  19.9841])

## 入力のすべての要素を範囲[min、max]にクランプし、結果として得られるテンソルを返します。


```
torch.clamp(input, min, max, out=None) → Tensor

```

In [0]:
a = torch.randn(4)
a

tensor([-0.3121, -0.2862, -0.8560,  0.4579])

In [0]:
torch.clamp(a, min=-0.5, max=0.5)

tensor([-0.3121, -0.2862, -0.5000,  0.4579])

## 入力の各要素をスカラー値で除算し、新しい結果のテンソルを返します

```
torch.div(input, value, out=None) → Tensor
```

In [0]:
a = torch.randn(5)
a

tensor([ 1.1178,  0.0843, -0.2130, -1.5707,  1.4731])

In [0]:
torch.div(a, 0.5)

tensor([ 2.2355,  0.1685, -0.4260, -3.1414,  2.9461])

テンソル入力の各要素は、テンソルその他の各要素で除算されます。結果のテンソルが返されます。入力とその他の形はブロードキャスト可能でなければならない


```
torch.div(input, other, out=None) → Tensor
```

In [0]:
a = torch.randn(4, 4)
a

tensor([[-0.0473, -0.1533,  0.9141,  1.1087],
        [ 0.2537, -1.6733,  0.4103, -0.7637],
        [-0.3552, -1.3587, -1.1927, -1.4380],
        [ 1.0660,  1.4844,  0.5598,  1.8169]])

In [0]:
b = torch.randn(4)
b

tensor([ 0.5163,  1.2114, -1.1202, -0.4395])

In [0]:
torch.div(a, b)

tensor([[-0.0916, -0.1266, -0.8160, -2.5224],
        [ 0.4914, -1.3813, -0.3663,  1.7374],
        [-0.6879, -1.1216,  1.0648,  3.2717],
        [ 2.0649,  1.2253, -0.4998, -4.1336]])

## 入力の要素の指数関数を持つ新しいテンソルを返します。

```
torch.exp(tensor, out=None) → Tensor
```

In [0]:
import math
torch.exp(torch.tensor([0, math.log(2)]))

tensor([ 1.,  2.])

## 入力の要素の自然対数を持つ新しいテンソルを返します。

```
torch.log(input, out=None) → Tensor
```

In [0]:
a = torch.randn(5)
a

In [0]:
torch.log(a)

tensor([-0.2589, -0.9586, -0.8487, -0.2385,     nan])

## 入力の各要素をスカラー値と乗算し、新しい結果テンソルを返します

```
torch.mul(input, value, out=None)
```

In [0]:
a = torch.randn(3)
a

tensor([ 0.4133, -0.4846, -2.0435])

In [0]:
torch.mul(a, 100)

tensor([  41.3257,  -48.4637, -204.3480])

## テンソル入力の各要素は、テンソルの他の各要素と乗算されます。結果のテンソルが返されます。

```
torch.mul(input, other, out=None)
```

In [0]:
a = torch.randn(4, 1)
a

tensor([[-0.0045],
        [ 0.0298],
        [-0.9267],
        [-1.9685]])

In [0]:
b = torch.randn(1, 4)
b

tensor([[-0.9873, -0.5971,  0.9693, -0.2684]])

In [0]:
torch.mul(a, b)

tensor([[ 0.0045,  0.0027, -0.0044,  0.0012],
        [-0.0294, -0.0178,  0.0289, -0.0080],
        [ 0.9149,  0.5533, -0.8982,  0.2487],
        [ 1.9435,  1.1753, -1.9081,  0.5283]])

## 指数で入力の各要素の力を受け取り、テンソルを返します


```
torch.pow(input, exponent, out=None) → Tensor
```


In [0]:
a = torch.randn(4)
a

tensor([-0.1423,  0.4893,  0.3765,  1.4706])

In [0]:
torch.pow(a, 2)

tensor([ 0.0203,  0.2394,  0.1417,  2.1626])

In [0]:
exp = torch.arange(1, 5)
exp

tensor([ 1.,  2.,  3.,  4.])

In [0]:
a = torch.arange(1, 5)
a

tensor([ 1.,  2.,  3.,  4.])

In [0]:
torch.pow(a, exp)

tensor([   1.,    4.,   27.,  256.])

## baseはスカラー浮動小数点値であり、入力はテンソルです。返されるテンソルは、入力と同じ形状です


```
torch.pow(base, input, out=None) → Tensor
```

In [0]:
exp = torch.arange(1, 5)
base = 2
torch.pow(base, exp)

tensor([  2.,   4.,   8.,  16.])

## 最も近い整数に丸められた入力の各要素を持つ新しいテンソルを返します。

```
torch.round(input, out=None) → Tensor
```


In [0]:
a = torch.randn(4)
a

tensor([ 1.4428, -0.6907, -0.0171, -1.3455])

In [0]:
torch.round(a)

tensor([ 1., -1., -0., -1.])

## 入力の要素のシグモイドで新しいテンソルを返します。

```
torch.sigmoid(input, out=None) → Tensor
```

In [0]:
a = torch.randn(4)
a

tensor([ 0.8995, -0.4620, -1.6185, -0.1272])

In [0]:
torch.sigmoid(a)

tensor([ 0.7108,  0.3865,  0.1654,  0.4682])

## 入力の要素の符号を持つ新しいテンソルを返します。

```
torch.sign(input, out=None) → Tensor
```

In [0]:
a = torch.randn(4)
a

tensor([-0.0832, -0.6300, -1.1471, -1.4952])

In [0]:
torch.sign(a)

tensor([-1., -1., -1., -1.])

## 入力の要素の平方根を持つ新しいテンソルを返します。

```
torch.sqrt(input, out=None) → Tensor
```

In [0]:
a = torch.randn(4)
a

tensor([-0.9294, -0.3600,  0.5535,  0.7477])

In [0]:
torch.sqrt(a)

tensor([    nan,     nan,  0.7440,  0.8647])

## 入力の要素の双曲線正接を持つ新しいテンソルを返します。

```
torch.tanh(input, out=None) → Tensor
```

In [0]:
a = torch.randn(4)
a

tensor([ 1.2648,  0.2383, -0.1682, -0.5257])

In [0]:
torch.tanh(a)

tensor([ 0.8524,  0.2339, -0.1666, -0.4821])

## 入力ベクトルが対角である正方行列を取得する



In [0]:
a = torch.randn(3)
a

tensor([ 0.3588, -0.2879,  0.3519])

In [0]:
torch.diag(a)

tensor([[ 0.3588,  0.0000,  0.0000],
        [ 0.0000, -0.2879,  0.0000],
        [ 0.0000,  0.0000,  0.3519]])

In [0]:
torch.diag(a, 1)

tensor([[ 0.0000,  0.3588,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.2879,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.3519],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

## batch1とbatch2に格納された行列のバッチ行列 - 行列積を実行

```
torch.bmm(batch1, batch2, out=None) → Tensor
```

In [0]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
res.size()

torch.Size([10, 3, 5])

## 2つのテンソルの内積を計算

In [0]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

## 2つのテンソルの行列積

In [0]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()
torch.Size([])

torch.Size([])

In [0]:
# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()
torch.Size([3])

torch.Size([3])

In [0]:
# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()
torch.Size([10, 3])

torch.Size([10, 3])

In [0]:
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()
torch.Size([10, 3, 5])

torch.Size([10, 3, 5])

In [0]:
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()
torch.Size([10, 3, 5])

torch.Size([10, 3, 5])

## 行列mat1とmat2の行列乗算を実行

```
torch.mm(mat1, mat2, out=None) → Tensor
```

In [0]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

tensor([[ 0.0469,  1.2265, -2.0321],
        [ 3.0320, -0.3066, -2.7597]])